apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-insurance-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-insurance
  template:
    metadata:
      labels:
        app: vehicle-insurance
    spec:
      containers:
      - name: app
        image: your-dockerhub/vehicle-insurance-api:latest
        ports:
        - containerPort: 80
