apiVersion: v1
kind: Service
metadata:
  name: vehicle-insurance-service
spec:
  selector:
    app: vehicle-insurance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
